# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dbbc9f38a7085363c561a6360770b5708822dcf6dd4d94cc8e59799c2e68f6e0f215d20a8574db89b3202596eb0a93d4c3f6e00f2e9f4a9ce6e21741a503667

test:
  secret_key_base: 04754c439e80041d2d1997329dfafb9a280a3631ec7aeb3682d53c85ecde07e2e14bf96cd4dcca7bc58dfd7732d2c5c8ecac72f570a12898f734507879efa75c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
