# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f42129079a841452a6ac97e2e53cbe8c4126582a431efd128e4143ba982a9fe0e4b46fedcc5c2bd16cee8a6e094cac49cf6b128f64a8674fb808174fd3d5f0f8

test:
  secret_key_base: aed8a95d9617f98664357f8f82c7cc458034458c8e3086dc7747ab86d8f690fce54a561ffd5c15119b7b6a9670bb619bf37429c289c31f4ebf21b5c7cdfd5c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
