# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96c80a94fb1fd35c57c3c4fee0e31bb822e1c822cf4e4ccf6de45c050f4fa081a3e5e1ca12d98aece1f340aafa15f0ddb6d9cb9b7f153c310e42056afd229a39

test:
  secret_key_base: b0528aa19e6ab2afcc2f89a2742783ca9061e2f3cbe754525c0b3e951012e6b487541f4fed3694aa75ff5d705a3c970fc18950c8cbe442dc234b3d3f19376e7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
