# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6489da4fb923692075ce3ee486d0be591c20a81c7c36fe5cec640270b06be3c8a4821b88174b96a2e646a926012e40a8c8ea2d2222e04163b7598c74e4a25604

test:
  secret_key_base: b9f75b2e1972a209d0aff7a7d0921f7c863ed38d9bede9303b11095f5309e90abb81831018fcdfd50b2893fe299bd1d8160000a7c7f89f20c4e9e8909543162e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
